#!/usr/bin/python
import re
import sys
import os


def findm(line):
	x_max = y_max = float("-inf")
	x_min = y_min = float("inf")
	for m in re.finditer(r"[\d\.]+\s[\d\.]+", line):
		x,y = m.group(0).split(" ")
		x = float(x)
		y = float(y)
		if x < x_min:
			x_min = x
		elif x > x_max:
			x_max = x

		if y < y_min:
			y_min = y
		elif y > y_max:
			y_max = y

	return x_min, x_max, y_min, y_max

if len(sys.argv) < 3:
	print("epsclip in out [margin=1]")
	exit(-1)

orig_eps = open(sys.argv[1])

x_max = y_max = float("-inf")
x_min = y_min = float("inf")
for line in orig_eps:
	if line.find("POLYGON") != -1:
		xmi, xma, ymi, yma = findm(line)
		if xmi < x_min:
			x_min = xmi
		elif xma > x_max:
			x_max = xma
		
		if ymi < y_min:
			y_min = ymi
		elif yma > y_max:
			y_max = yma


margin = 10
if len(sys.argv) > 3:
	margin = float(sys.argv[3])

x0 = x_min - margin
x1 = x_max + margin
y0 = y_min - margin
y1 = y_max + margin

orig_eps.seek(0)

clip_eps = open(sys.argv[2],"w")

lines = orig_eps.readlines()

for i in range(len(lines)):
	if lines[i].find(r"%%BoundingBox:") != -1:
		lines[i] = "%%%%BoundingBox: %f %f %f %f\n"	% (x0, y0, x1, y1)
clip_eps.writelines(lines)
clip_eps.close()
os.system("open "+sys.argv[2])
